create table public.empleados (
  id bigint generated by default as identity not null,
  nombre text not null,
  apellido text not null,
  email text not null,
  telefono text not null,
  cargo text not null,
  departamento text not null,
  salario numeric(10, 2) not null,
  created_at timestamp with time zone not null default now(),
  constraint empleados_pkey primary key (id),
  constraint empleados_email_key unique (email)
) TABLESPACE pg_default;